export const DISCOUNTS = "discounts";
export const USERS = "user";
export const MENUCATEGORIES = "menucategories";
export const TABLE = "tables";
export const ORDERS = "order";
export const MENUITEMS = "menuitem";
export const RESERVATION = "reservations";
export const CUSTOMERS = 'customer';
export const PAYMENTS = 'payments';
export const REPORTS = 'report';
export const INGREDIENTS = 'ingredients';
export const NAVMENU = 'navmenu';


// discounts
export const GET_DISCOUNTS_TYPE_SUCCESS = "GET_DISCOUNTS_TYPE_SUCCESS";
export const GET_DISCOUNTS_TYPE_ERROR = "GET_DISCOUNTS_TYPE_ERROR";
export const UPDATE_DISCOUNTS_TYPE_SUCCESS = "UPDATE_DISCOUNTS_TYPE_SUCCESS";
export const UPDATE_DISCOUNTS_TYPE_ERROR = "UPDATE_DISCOUNTS_TYPE_ERROR";
export const DELETE_DISCOUNTS_TYPE_SUCCESS = "DELETE_DISCOUNTS_TYPE_SUCCESS";
export const DELETE_DISCOUNTS_TYPE_ERROR = "DELETE_DISCOUNTS_TYPE_ERROR";
export const GET_ACTIVE_DISCOUNTS_TYPE_SUCCESS = "GET_ACTIVE_DISCOUNTS_TYPE_SUCCESS";
export const GET_ACTIVE_DISCOUNTS_TYPE_ERROR = "GET_ACTIVE_DISCOUNTS_TYPE_ERROR";

// users
export const GET_USERS_TYPE_SUCCESS = "GET_USERS_TYPE_SUCCESS";
export const GET_USERS_TYPE_ERROR = "GET_USERS_TYPE_ERROR";
export const UPDATE_USERS_TYPE_SUCCESS = "UPDATE_USERS_TYPE_SUCCESS";
export const UPDATE_USERS_TYPE_ERROR = "UPDATE_USERS_TYPE_ERROR";
export const DELETE_USERS_TYPE_SUCCESS = "DELETE_USERS_TYPE_SUCCESS";
export const DELETE_USERS_TYPE_ERROR = "DELETE_USERS_TYPE_ERROR";
export const CREATE_USERS_TYPE_SUCCESS = "CREATE_USERS_TYPE_SUCCESS";
export const CREATE_USERS_TYPE_ERROR = "CREATE_USERS_TYPE_ERROR";
export const CHANG_PASSWORD_USERS_TYPE_SUCCESS = "CHANG_PASSWORD_USERS_TYPE_SUCCESS";
export const CHANG_PASSWORD_TYPE_ERROR = "CHANG_PASSWORD_TYPE_ERROR";

// menucategoriesReducer
export const GET_MENUCATEGORIES_TYPE_SUCCESS = "GET_MENUCATEGORIES_TYPE_SUCCESS";
export const GET_MENUCATEGORIES_TYPE_ERROR = "GET_MENUCATEGORIES_TYPE_ERROR";
export const UPDATE_MENUCATEGORIES_TYPE_SUCCESS = "UPDATE_MENUCATEGORIES_TYPE_SUCCESS";
export const UPDATE_MENUCATEGORIES_TYPE_ERROR = "UPDATE_MENUCATEGORIES_TYPE_ERROR";
export const DELETE_MENUCATEGORIES_TYPE_SUCCESS = "DELETE_MENUCATEGORIES_TYPE_SUCCESS";
export const DELETE_MENUCATEGORIES_TYPE_ERROR = "DELETE_MENUCATEGORIES_TYPE_ERROR";
export const GET_ALL_MENUCATEGORIES_TYPE_SUCCESS = "GET_ALL_MENUCATEGORIES_TYPE_SUCCESS";
export const GET_ALL_MENUCATEGORIES_TYPE_ERROR = "GET_ALL_MENUCATEGORIES_TYPE_ERROR";

// table
export const GET_EMPTYTABLE_TYPE_SUCCESS = "GET_EMPTYTABLE_TYPE_SUCCESS";
export const GET_EMPTYTABLE_TYPE_ERROR = "GET_EMPTYTABLE_TYPE_ERROR";
export const GET_TABLE_TYPE_SUCCESS = "GET_TABLE_TYPE_SUCCESS";
export const GET_TABLE_TYPE_ERROR = "GET_TABLE_TYPE_ERROR";
export const UPDATE_STATUS_TABLE_TYPE_SUCCESS = "UPDATE_STATUS_TABLE_TYPE_SUCCESS";
export const UPDATE_STATUS_TABLE_TYPE_ERROR = "UPDATE_STATUS_TABLE_TYPE_ERROR";
export const DELETE_TABLE_TYPE_SUCCESS = "DELETE_TABLE_TYPE_SUCCESS";
export const DELETE_TABLE_TYPE_ERROR = "DELETE_TABLE_TYPE_ERROR";
export const UPDATE_TABLE_TYPE_SUCCESS = "UPDATE_TABLE_TYPE_SUCCESS";
export const UPDATE_TABLE_TYPE_ERROR = "UPDATE_TABLE_TYPE_ERROR";

// orders
export const CREATE_ORDERS_TYPE_SUCCESS = "CREATE_ORDERS_TYPE_SUCCESS";
export const CREATE_ORDERS_TYPE_ERROR = "CREATE_ORDERS_TYPE_ERROR";
export const GET_ORDERS_TYPE_SUCCESS = "GET_ORDERS_TYPE_SUCCESS";
export const GET_ORDERS_TYPE_ERROR = "GET_ORDERS_TYPE_ERROR";
export const UPDATE_ORDERS_STATUS_TYPE_SUCCESS = "UPDATE_ORDERS_STATUS_TYPE_SUCCESS";
export const UPDATE_ORDERS_STATUS_TYPE_ERROR = "UPDATE_ORDERS_STATUS_TYPE_ERROR";
export const GET_ORDERS_ID_TYPE_SUCCESS = "GET_ORDERS_ID_TYPE_SUCCESS";
export const GET_ORDERS_ID_TYPE_ERROR = "GET_ORDERS_ID_TYPE_ERROR";
export const UPDATE_ORDERSITEMS_TYPE_SUCCESS = "UPDATE_ORDERSITEMS_TYPE_SUCCESS";
export const UPDATE_ORDERSITEMS_TYPE_ERROR = "UPDATE_ORDERSITEMS_TYPE_ERROR";

// menuitem
export const GET_MENUITEMS_TYPE_SUCCESS = "GET_MENUITEMS_TYPE_SUCCESS";
export const GET_MENUITEMS_TYPE_ERROR = "GET_MENUITEMS_TYPE_ERROR";
export const UPDATE_MENUITEMS_TYPE_SUCCESS = "UPDATE_MENUITEMS_TYPE_SUCCESS";
export const UPDATE_MENUITEMS_TYPE_ERROR = "UPDATE_MENUITEMS_TYPE_ERROR";

// reservations
export const GET_RESERVATION_TYPE_SUCCESS = "GET_RESERVATION_TYPE_SUCCESS";
export const GET_RESERVATION_TYPE_ERROR = "GET_RESERVATION_TYPE_ERROR";
export const GET_LIST_RESERVATION_TYPE_SUCCESS = "GET_LIST_RESERVATION_TYPE_SUCCESS";
export const GET_LIST_RESERVATION_TYPE_ERROR = "GET_LIST_RESERVATION_TYPE_ERROR";
export const UPDATE_RESERVATION_TYPE_SUCCESS = "UPDATE_RESERVATION_TYPE_SUCCESS";
export const UPDATE_RESERVATION_TYPE_ERROR = "UPDATE_RESERVATION_TYPE_ERROR";
export const ACCEPT_RESERVATION_TYPE_SUCCESS = "ACCEPT_RESERVATION_TYPE_SUCCESS";
export const ACCEPT_RESERVATION_TYPE_ERROR = "ACCEPT_RESERVATION_TYPE_ERROR";
export const CREATE_RESERVATION_TYPE_SUCCESS = "CREATE_RESERVATION_TYPE_SUCCESS";
export const CREATE_RESERVATION_TYPE_ERROR = "CREATE_RESERVATION_TYPE_ERROR";

// customer
export const GET_CUSTOMERS_TYPE_SUCCESS = "GET_CUSTOMERS_TYPE_SUCCESS";
export const GET_CUSTOMERS_TYPE_ERROR = "GET_CUSTOMERS_TYPE_ERROR";
export const UPDATE_CUSTOMERS_TYPE_SUCCESS = "UPDATE_CUSTOMERS_TYPE_SUCCESS";
export const UPDATE_CUSTOMERS_TYPE_ERROR = "UPDATE_CUSTOMERS_TYPE_ERROR";

// payments
export const CREATE_PAYMENTS_TYPE_SUCCESS = "CREATE_PAYMENTS_TYPE_SUCCESS";
export const CREATE_PAYMENTS_TYPE_ERROR = "CREATE_PAYMENTS_TYPE_ERROR";

// report
export const REPORTS_REVENUE_BY_MONTH_TYPE_SUCCESS = "REPORTS_REVENUE_BY_MONTH_TYPE_SUCCESS";
export const REPORTS_REVENUE_BY_MONTH_TYPE_ERROR = "REPORTS_REVENUE_BY_MONTH_TYPE_ERROR";
export const REPORTS_COUNT_ORDERS_BY_MONTH_TYPE_SUCCESS = "REPORTS_COUNT_ORDERS_BY_MONTH_TYPE_SUCCESS";
export const REPORTS_COUNT_ORDERS_BY_MONTH_TYPE_ERROR = "REPORTS_COUNT_ORDERS_BY_MONTH_TYPE_ERROR";
export const REPORTS_REVENUE_BY_CATEGORY_TYPE_SUCCESS = "REPORTS_REVENUE_BY_CATEGORY_TYPE_SUCCESS";
export const REPORTS_REVENUE_BY_CATEGORY_TYPE_ERROR = "REPORTS_REVENUE_BY_CATEGORY_TYPE_ERROR";
export const REPORTS_COUNT_ORDERS_TODAY_TYPE_SUCCESS = "REPORTS_COUNT_ORDERS_TODAY_TYPE_SUCCESS";
export const REPORTS_COUNT_ORDERS_TODAY_TYPE_ERROR = "REPORTS_COUNT_ORDERS_TODAY_TYPE_ERROR";
export const REPORTS_REVENUE_ORDERS_TODAY_TYPE_SUCCESS = "REPORTS_REVENUE_ORDERS_TODAY_TYPE_SUCCESS";
export const REPORTS_REVENUE_ORDERS_TODAY_TYPE_ERROR = "REPORTS_REVENUE_ORDERS_TODAY_TYPE_ERROR";
export const REPORTS_COUNT_CUSTOMER_THIS_YEAR_TYPE_SUCCESS = "REPORTS_COUNT_CUSTOMER_THIS_YEAR_TYPE_SUCCESS";
export const REPORTS_COUNT_CUSTOMER_THIS_YEAR_TYPE_ERROR = "REPORTS_COUNT_CUSTOMER_THIS_YEAR_TYPE_ERROR";
export const REPORTS_ORDER_CANCELLATION_RATE_TYPE_SUCCESS = "REPORTS_ORDER_CANCELLATION_RATE_TYPE_SUCCESS";
export const REPORTS_ORDER_CANCELLATION_RATE_TYPE_ERROR = "REPORTS_ORDER_CANCELLATION_RATE_TYPE_ERROR";
export const REPORTS_ORDER_RECENT_TYPE_SUCCESS = "REPORTS_ORDER_RECENT_TYPE_SUCCESS";
export const REPORTS_ORDER_RECENT_TYPE_ERROR = "REPORTS_ORDER_RECENT_TYPE_ERROR";
export const REPORTS_TOP_SELLING_TYPE_SUCCESS = "REPORTS_TOP_SELLING_TYPE_SUCCESS";
export const REPORTS_TOP_SELLING_TYPE_ERROR = "REPORTS_TOP_SELLING_TYPE_ERROR";

// ingredients
export const GET_INGREDIENTS_TYPE_SUCCESS = "GET_INGREDIENTS_TYPE_SUCCESS";
export const GET_INGREDIENTS_TYPE_ERROR = "GET_INGREDIENTS_TYPE_ERROR";
export const UPDATE_INGREDIENTS_TYPE_SUCCESS = "UPDATE_INGREDIENTS_TYPE_SUCCESS";
export const UPDATE_INGREDIENTS_TYPE_ERROR = "UPDATE_INGREDIENTS_TYPE_ERROR";
export const DELETE_INGREDIENTS_TYPE_SUCCESS = "DELETE_INGREDIENTS_TYPE_SUCCESS";
export const DELETE_INGREDIENTS_TYPE_ERROR = "DELETE_INGREDIENTS_TYPE_ERROR";
export const UPDATE_EXPIRED_INGREDIENTS_TYPE_SUCCESS = "UPDATE_EXPIRED_INGREDIENTS_TYPE_SUCCESS";
export const UPDATE_EXPIRED_INGREDIENTS_TYPE_ERROR = "UPDATE_EXPIRED_INGREDIENTS_TYPE_ERROR";
export const CHECK_INGREDIENTS_TYPE_SUCCESS = "CHECK_INGREDIENTS_TYPE_SUCCESS"
export const CHECK_INGREDIENTS_TYPE_ERROR = "CHECK_INGREDIENTS_TYPE_ERROR"
export const UPDATE_VALIDATE_INGREDIENTS_TYPE_SUCCESS = "UPDATE_VALIDATE_INGREDIENTS_TYPE_SUCCESS"
export const UPDATE_VALIDATE_INGREDIENTS_TYPE_ERROR = "UPDATE_VALIDATE_INGREDIENTS_TYPE_ERROR"

export const GET_INFORMATION_TYPE_SUCCESS = "GET_INFORMATION_TYPE_SUCCESS";
export const GET_INFORMATION_TYPE_ERROR = "GET_INFORMATION_TYPE_ERROR";
export const UPDATE_INFORMATION_TYPE_SUCCESS = "UPDATE_INFORMATION_TYPE_SUCCESS";
export const UPDATE_INFORMATION_TYPE_ERROR = "UPDATE_INFORMATION_TYPE_ERROR";

// SUCCESS
export const GET_NAVMENU_TYPE_SUCCESS = "GET_NAVMENU_TYPE_SUCCESS";
export const DELETE_NAVMENU_TYPE_SUCCESS = "DELETE_NAVMENU_TYPE_SUCCESS";
export const UPDATE_NAVMENU_TYPE_SUCCESS = "UPDATE_NAVMENU_TYPE_SUCCESS";
export const GET_NAVMENU_SIDEBAR_TYPE_SUCCESS = "GET_NAVMENU_SIDEBAR_TYPE_SUCCESS";

// ERROR
export const GET_NAVMENU_TYPE_ERROR = "GET_NAVMENU_TYPE_ERROR";
export const DELETE_NAVMENU_TYPE_ERROR = "DELETE_NAVMENU_TYPE_ERROR";
export const UPDATE_NAVMENU_TYPE_ERROR = "UPDATE_NAVMENU_TYPE_ERROR";
export const GET_NAVMENU_SIDEBAR_TYPE_ERROR = "GET_NAVMENU_SIDEBAR_TYPE_ERROR";
